### Teste de voz para o assistente
GET http://127.0.0.1:5000/assistente


### Teste de texto para o assistente
# POST http://127.0.0.1:5000/teste-texto
# Content-Type: application/json

# {
#   "entrada": "estou procurando dipirona"
# }
